# SPDX-FileCopyrightText: 2022 Forschungszentrum Jülich
#
# SPDX-License-Identifier: CC0-1.0

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install "poetry>=1.2.0,<1.3.0"
      - poetry config virtualenvs.create false
      - poetry install --with docs

# Build documentation in the docs/source directory with Sphinx
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true