# SPDX-FileCopyrightText: 2023 German Aerospace Center (DLR)
#
# SPDX-License-Identifier: CC0-1.0

[harvest]
from = [ "cff", "git" ]

[harvest.cff]
validate = false

[deposit]
target = "invenio"

[deposit.invenio]
site_url = "https://sandbox.zenodo.org"
communities = ["zenodo"]
access_right = "open"

[deposit.invenio.api_paths]
depositions = "api/deposit/depositions"
licenses = "api/licenses"
communities = "api/communities"
