# SPDX-FileCopyrightText: 2023 German Aerospace Center (DLR)
#
# SPDX-License-Identifier: CC0-1.0

[harvest]
from = [ "cff", "git" ]

[harvest.cff]
validate = false

[deposit]
target = "invenio_rdm"

[deposit.invenio_rdm]
site_url = "https://sandbox.zenodo.org"
communities = ["zenodo"]
access_right = "open"

[deposit.invenio_rdm.api_paths]
depositions = "api/deposit/depositions"
licenses = "api/vocabularies/licenses"
communities = "api/communities"
