# SPDX-FileCopyrightText: 2022 German Aerospace Center (DLR)
#
# SPDX-License-Identifier: CC0-1.0

# SPDX-FileContributor: Stephan Druskat
# SPDX-FileContributor: Michael Meinel
# SPDX-FileContributor: David Pape

[tool.poetry]
name = "hermes"
version = "0.9.0"
description = "Workflow to publish research software with rich metadata"
homepage = "https://software-metadata.pub"
license = "Apache-2.0"
authors = [
    "Stephan Druskat <stephan.druskat@dlr.de>",
    "Michael Meinel <michael.meinel@dlr.de>",
    "Oliver Bertuch <o.bertuch@fz-juelich.de>",
    "Jeffrey Kelling <j.kelling@hzdr.de>",
    "Oliver Knodel <o.knodel@hzdr.de>",
    "David Pape <d.pape@hzdr.de>",
]

readme = "README.md"
repository = "https://github.com/hermes-hmc/workflow"
documentation = "https://docs.software-metadata.pub"
keywords = ["publishing", "metadata", "automation"]

include = [
    "hermes/schema/*.json",
]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1"
"ruamel.yaml" = "^0.17.21"
jsonschema = "^3.0.0"
pyld = "^2.0.3"
cffconvert = "^2.0.0"
toml = "^0.10.2"
pyparsing = "^3.0.9"
requests = "^2.28.1"

# Packages for developers
[tool.poetry.group.dev.dependencies]
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
taskipy = "^1.10.3"
flake8 = "^5.0.4"
requests-mock = "^1.10.0"

# Packages for developers for creating documentation
[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
Sphinx = "^4.5.0"
# Sphinx - Additional modules
myst-parser = "^0.18.0"
sphinx-book-theme = "^0.3.3"
sphinx-favicon = "^0.2"
sphinxcontrib-contentui = "^0.2.5"
sphinxcontrib-images = "^0.9.4"
sphinx-icon = "^0.1.2"
sphinx-autobuild = "^2021.3.14"
sphinx-autoapi = "^2.0.0"
sphinxemoji = "^0.2.0"
sphinxext-opengraph = "^0.6.3"
sphinx-click = "^4.4.0"
sphinxcontrib-mermaid="^0.8.1"
sphinx-togglebutton="^0.3.2"
reuse = "^1.1.2"

[tool.poetry.plugins.console_scripts]
hermes = "hermes.cli:main"

[tool.poetry.plugins."hermes.harvest"]
cff = "hermes.commands.harvest.cff:harvest_cff"
codemeta = "hermes.commands.harvest.codemeta:harvest_codemeta"
git = "hermes.commands.harvest.git:harvest_git"

[tool.poetry.plugins."hermes.preprocess"]
cff_add_name = "hermes.commands.process.cff:add_name"

git = "hermes.commands.process.git:process"
git_add_contributors = "hermes.commands.process.git:add_contributors"
git_add_branch = "hermes.commands.process.git:add_branch"

[tool.poetry.plugins."hermes.deposit.prepare"]
invenio = "hermes.commands.deposit.invenio:prepare"
invenio_rdm = "hermes.commands.deposit.invenio_rdm:prepare"
file = "hermes.commands.deposit.file:dummy_noop"

[tool.poetry.plugins."hermes.deposit.map"]
invenio = "hermes.commands.deposit.invenio:map_metadata"
invenio_rdm = "hermes.commands.deposit.invenio_rdm:map_metadata"
file = "hermes.commands.deposit.file:map_metadata"

[tool.poetry.plugins."hermes.deposit.create_initial_version"]
invenio = "hermes.commands.deposit.invenio:create_initial_version"
invenio_rdm = "hermes.commands.deposit.invenio_rdm:create_initial_version"
file = "hermes.commands.deposit.file:dummy_noop"

[tool.poetry.plugins."hermes.deposit.create_new_version"]
invenio = "hermes.commands.deposit.invenio:create_new_version"
invenio_rdm = "hermes.commands.deposit.invenio_rdm:create_new_version"
file = "hermes.commands.deposit.file:dummy_noop"

[tool.poetry.plugins."hermes.deposit.update_metadata"]
invenio = "hermes.commands.deposit.invenio:update_metadata"
invenio_rdm = "hermes.commands.deposit.invenio_rdm:update_metadata"
file = "hermes.commands.deposit.file:dummy_noop"

[tool.poetry.plugins."hermes.deposit.delete_artifacts"]
invenio = "hermes.commands.deposit.invenio:delete_artifacts"
invenio_rdm = "hermes.commands.deposit.invenio_rdm:delete_artifacts"
file = "hermes.commands.deposit.file:dummy_noop"

[tool.poetry.plugins."hermes.deposit.upload_artifacts"]
invenio = "hermes.commands.deposit.invenio:upload_artifacts"
invenio_rdm = "hermes.commands.deposit.invenio_rdm:upload_artifacts"
file = "hermes.commands.deposit.file:dummy_noop"

[tool.poetry.plugins."hermes.deposit.publish"]
invenio = "hermes.commands.deposit.invenio:publish"
invenio_rdm = "hermes.commands.deposit.invenio_rdm:publish"
file = "hermes.commands.deposit.file:publish"

[tool.poetry.plugins."hermes.postprocess"]
config_invenio_record_id = "hermes.commands.postprocess.invenio:config_record_id"
config_invenio_rdm_record_id = "hermes.commands.postprocess.invenio_rdm:config_record_id"
cff_doi = "hermes.commands.postprocess.invenio:cff_doi"

[tool.taskipy.tasks]
docs-build = "poetry run sphinx-build -M html docs/source docs/build -W"
docs-clean = "poetry run sphinx-build -M clean docs/source docs/build"
docs-live = "poetry run sphinx-autobuild docs/source docs/build"
flake8 = "poetry run flake8 ./test/ ./src/ --count --select=E9,F63,F7,F82 --statistics"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
